server: "hub-cloud.browserstack.com"
user: "BROWSERSTACK_USERNAME"
key: "BROWSERSTACK_AUTH_KEY"

common_caps:
  "build": "cucumber-browserstack"
  "browserstack.debug": true

  
browser_caps:
  -
    "device": "iPhone 7"
    "app": "bs://28b4d9102c7d76407644d4a496c6d1ac14fd3590"
    "name": "single_test"
    "browserstack.video": "true"

