server: "hub-cloud.browserstack.com"
user: "BROWSERSTACK_USERNAME"
key: "BROWSERSTACK_ACCESS_KEY"

common_caps:
  "build": "cucumber-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "device": "Google Pixel"
    "app": "bs://<hashed app-id>"
    "name": "parallel_test"
  -
    "device": "Google Nexus 5"
    "app": "bs://<hashed app-id>"
    "name": "parallel_test"
  -
    "device": "Samsung Galaxy S7"
    "app": "bs://<hashed app-id>"
    "name": "parallel_test"
